database:
  dbUrl: ./storage/macauth.db
httpServer:
  address: 0.0.0.0:2800
  idleTimeout: 90s
  readTimeout: 10s
  writeTimeout: 20s
pem:
  privPath: ./storage/keys/private.pem
  pubPath: ./storage/keys/public.pem
log:
  logPath: ./storage/macauth.log